stages:
  data_ingestion:
    cmd: python src/components/data_ingestion.py
    deps:
      - src/components/data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion

  data_preprocessing:
    cmd: python src/components/data_preprocessing.py
    deps:
      - src/components/data_preprocessing.py
      - artifacts/data_ingestion
    outs:
      - artifacts/data_preprocessing

  model_training:
    cmd: python src/pipeline/train_pipeline.py
    deps:
      - src/pipeline/train_pipeline.py
      - artifacts/data_preprocessing
    outs:
      - artifacts/model_training/covid_model.h5

  model_evaluation:
    cmd: python src/components/model_evaluation.py
    deps:
      - src/components/model_evaluation.py
      - artifacts/model_training/covid_model.h5
    outs:
      - artifacts/model_evaluation/metrics.json
